### ISSUE TITLE
Supporting multiple :starts-after dependencies

### ISSUE THREAD

**Issue by lvh** [redstarssystems/gantt#2]
Right now, `:starts-after` expects a single task alias. This ostensibly means there is no way to express a task that has multiple dependencies. However, PlantUML supports this; some examples here: https://github.com/mattjhayes/PlantUML-Examples/blob/master/docs/Diagram-Types/source/gantt.md

**Comment by mikeananev** [comment]
Fixed in release 0.1.9
Now :starts-after accepts not only alias but vector of aliases too. Docs updated.

**Comment by lvh** [comment]
Whoa, thanks!
